default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: language_community_development
  host: localhost

test:
  <<: *default
  database: language_community_test

production:
  <<: *default
  database: language_community_production
  username: language_community
  password: <%= ENV['LANGUAGE_COMMUNITY_DATABASE_PASSWORD'] %>
