default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: placty_development
  host: localhost

test:
  <<: *default
  database: placty_test

production:
  <<: *default
  url: <%= ENV['HEROKU_POSTGRESQL_ROSE_URL'] %>
  adapter: postgresql
