class TimeZone < ActiveHash::Base
  self.data = [
    {id: 1, ja_name: "南アフリカ標準時", en_name: "Africa/Johannesburg", both: "南アフリカ標準時(Africa/Johannesburg)"  },
    {id: 2, ja_name: "西アフリカ時間", en_name: "Africa/Lagos", both: "西アフリカ時間(Africa/Lagos)" },
    {id: 3, ja_name: "西アフリカ時間", en_name: "Africa/Windhoek", both: "西アフリカ時間(Africa/Windhoek)" },
    {id: 4, ja_name: "ハワイ - アリューシャン標準時", en_name: "America/Adak", both: "ハワイ - アリューシャン標準時(America/Adak)" },
    {id: 5, ja_name: "アラスカ標準時", en_name: "America/Anchorage", both: "アラスカ標準時(America/Anchorage)" },
    {id: 6, ja_name: "アルゼンチン時間", en_name: "America/Argentina/Buenos_Aires", both: "アルゼンチン時間(America/Argentina/Buenos_Aires)" },
    {id: 7, ja_name: "コロンビア時間", en_name: "America/Bogota", both: "コロンビア時間(America/Bogota)" },
    {id: 8, ja_name: "ベネズエラ時間", en_name: "America/Caracas", both: "ベネズエラ時間(America/Caracas)" },
    {id: 9, ja_name: "中部標準時", en_name: "America/Chicago", both: "中部標準時(America/Chicago)" },
    {id: 10, ja_name: "山地標準時", en_name: "America/Denver", both: "山地標準時(America/Denver)" },
    {id: 11, ja_name: "西グリーンランド時間", en_name: "America/Godthab", both: "西グリーンランド時間(America/Godthab)" },
    {id: 12, ja_name: "中部標準時", en_name: "America/Guatemala", both: "中部標準時(America/Guatemala)" },
    {id: 13, ja_name: "大西洋標準時", en_name: "America/Halifax", both: "大西洋標準時(America/Halifax)" },
    {id: 14, ja_name: "太平洋標準時", en_name: "America/Los_Angeles", both: "太平洋標準時(America/Los_Angeles)" },
    {id: 15, ja_name: "ウルグアイ時間", en_name: "America/Montevideo", both: "ウルグアイ時間(America/Montevideo)" },
    {id: 16, ja_name: "東部標準時", en_name: "America/New_York", both: "東部標準時(America/New_York)" },
    {id: 17, ja_name: "フェルナンド・デ・ノローニャ時間", en_name: "America/Noronha", both: "フェルナンド・デ・ノローニャ時間(America/Noronha)" },
    {id: 18, ja_name: "山地標準時", en_name: "America/Phoenix", both: "山地標準時(America/Phoenix)" },
    {id: 19, ja_name: "チリ時間", en_name: "America/Santiago", both: "チリ時間(America/Santiago)" },
    {id: 20, ja_name: "大西洋標準時", en_name: "America/Santo_Domingo", both: "大西洋標準時(America/Santo_Domingo)" },
    {id: 21, ja_name: "ニューファンドランド標準時", en_name: "America/St_Johns", both: "ニューファンドランド標準時(America/St_Johns)" },
    {id: 22, ja_name: "アラビア標準時", en_name: "Asia/Baghdad", both: "アラビア標準時(Asia/Baghdad)" },
    {id: 23, ja_name: "アゼルバイジャン時間", en_name: "Asia/Baku", both: "アゼルバイジャン時間(Asia/Baku)" },
    {id: 24, ja_name: "東ヨーロッパ時間", en_name: "Asia/Beirut", both: "東ヨーロッパ時間(Asia/Beirut)"},
    {id: 25, ja_name: "バングラデシュ時間", en_name: "Asia/Dhaka", both: "バングラデシュ時間(Asia/Dhaka)" },
    {id: 26, ja_name: "湾岸標準時", en_name: "Asia/Dubai", both: "湾岸標準時(Asia/Dubai)" },
    {id: 27, ja_name: "イルクーツク時間", en_name: "Asia/Irkutsk", both: "イルクーツク時間(Asia/Irkutsk)" },
    {id: 28, ja_name: "西インドネシア時間", en_name: "Asia/Jakarta" , both: "西インドネシア時間(Asia/Jakarta)"},
    {id: 29, ja_name: "アフガニスタン時間", en_name: "Asia/Kabul" , both: "アフガニスタン時間(Asia/Kabul)"},
    {id: 30, ja_name: "ペトロパブロフスクカムチャツキー時間", en_name: "Asia/Kamchatka", both: "ペトロパブロフスクカムチャツキー時間(Asia/Kamchatka)" },
    {id: 31, ja_name: "パキスタン時間", en_name: "Asia/Karachi", both: "パキスタン時間(Asia/Karachi)" },
    {id: 32, ja_name: "ネパール時間", en_name: "Asia/Kathmandu", both: "ネパール時間(Asia/Kathmandu)" },
    {id: 33, ja_name: "インド標準時", en_name: "Asia/Kolkata", both: "インド標準時(Asia/Kolkata)" },
    {id: 34, ja_name: "クラスノヤルスク時間", en_name: "Asia/Krasnoyarsk", both: "クラスノヤルスク時間(Asia/Krasnoyarsk)" },
    {id: 35, ja_name: "オムスク時間", en_name: "Asia/Omsk", both: "オムスク時間(Asia/Omsk)" },
    {id: 36, ja_name: "ミャンマー時間", en_name: "Asia/Rangoon", both: "ミャンマー時間(Asia/Rangoon)" },
    {id: 37, ja_name: "中国標準時", en_name: "Asia/Shanghai", both: "中国標準時(Asia/Shanghai)" },
    {id: 38, ja_name: "イラン標準時", en_name: "Asia/Tehran", both: "イラン標準時(Asia/Tehran)" },
    {id: 39, ja_name: "日本標準時", en_name: "Asia/Tokyo", both: "日本標準時(Asia/Tokyo)" },
    {id: 40, ja_name: "ウラジオストク時間", en_name: "Asia/Vladivostok", both: "ウラジオストク時間(Asia/Vladivostok)" },
    {id: 41, ja_name: "ヤクーツク時間", en_name: "Asia/Yakutsk", both: "ヤクーツク時間(Asia/Yakutsk)" },
    {id: 42, ja_name: "エカテリンブルグ時間", en_name: "Asia/Yekaterinburg", both: "エカテリンブルグ時間(Asia/Yekaterinburg)" },
    {id: 43, ja_name: "アゾレス時間", en_name: "Atlantic/Azores", both: "アゾレス時間(Atlantic/Azores)" },
    {id: 44, ja_name: "カーボベルデ時間", en_name: "Atlantic/Cape_Verde", both: "カーボベルデ時間(Atlantic/Cape_Verde)" },
    {id: 45, ja_name: "中部標準時 （南オーストラリア）", en_name: "Australia/Adelaide", both: "中部標準時 （南オーストラリア）(Australia/Adelaide)" },
    {id: 46, ja_name: "東部標準時 （クイーンズランド）", en_name: "Australia/Brisbane", both: "東部標準時 （クイーンズランド）(Australia/Brisbane)" },
    {id: 47, ja_name: "中部標準時 （ノーザンテリトリー）", en_name: "Australia/Darwin", both: "中部標準時 （ノーザンテリトリー）(Australia/Darwin)" },
    {id: 48, ja_name: "中西部標準時 （オーストラリア）", en_name: "Australia/Eucla", both: "中西部標準時 （オーストラリア）(Australia/Eucla)" },
    {id: 49, ja_name: "ロードハウ島標準時", en_name: "Australia/Lord_Howe", both: "ロードハウ島標準時(Australia/Lord_Howe)" },
    {id: 50, ja_name: "東部標準時 （ニューサウスウェールズ）", en_name: "Australia/Sydney", both: "東部標準時 （ニューサウスウェールズ）(Australia/Sydney)" },
    {id: 51, ja_name: "GMT-12:00", en_name: "Etc/GMT+12", both: "GMT-12:00(Etc/GMT+12)" },
    {id: 52, ja_name: "中部ヨーロッパ時間", en_name: "Europe/Berlin", both: "中部ヨーロッパ時間(Europe/Berlin)"},
    {id: 53, ja_name: "グリニッジ標準時", en_name: "Europe/London" , both: "グリニッジ標準時(Europe/London)"},
    {id: 54, ja_name: "モスクワ標準時", en_name: "Europe/Moscow" , both: "モスクワ標準時(Europe/Moscow)"},
    {id: 55, ja_name: "西サモア時間", en_name: "Pacific/Apia", both: "西サモア時間(Pacific/Apia)" },
    {id: 56, ja_name: "ニュージーランド標準時", en_name: "Pacific/Auckland", both: "ニュージーランド標準時(Pacific/Auckland)" },
    {id: 57, ja_name: "チャタム標準時", en_name: "Pacific/Chatham", both: "チャタム標準時(Pacific/Chatham)" },
    {id: 58, ja_name: "イースター島時間", en_name: "Pacific/Easter", both: "イースター島時間(Pacific/Easter)" },
    {id: 59, ja_name: "ガンビア時間", en_name: "Pacific/Gambier", both: "ガンビア時間(Pacific/Gambier)" },
    {id: 60, ja_name: "ハワイ標準時", en_name: "Pacific/Honolulu", both: "ハワイ標準時(Pacific/Honolulu)" },
    {id: 61, ja_name: "ライン諸島時間", en_name: "Pacific/Kiritimati", both: "ライン諸島時間(Pacific/Kiritimati)" },
    {id: 62, ja_name: "マーシャル島時間", en_name: "Pacific/Majuro", both: "マーシャル島時間(Pacific/Majuro)" },
    {id: 63, ja_name: "マルケサス時間", en_name: "Pacific/Marquesas", both: "マルケサス時間(Pacific/Marquesas)" },
    {id: 64, ja_name: "ノーフォーク時間", en_name: "Pacific/Norfolk", both: "ノーフォーク時間(Pacific/Norfolk)" },
    {id: 65, ja_name: "ニューカレドニア時間", en_name: "Pacific/Noumea", both: "ノーフォーク時間(Pacific/Noumea)" },
    {id: 66, ja_name: "サモア標準時", en_name: "Pacific/Pago_Pago", both: "サモア標準時(Pacific/Pago_Pago)" },
    {id: 67, ja_name: "ピトケルン島標準時", en_name: "Pacific/Pitcairn", both: "ピトケルン島標準時(Pacific/Pitcairn)" },
    {id: 68, ja_name: "トンガ時間", en_name: "Pacific/Tongatapu", both: "トンガ時間(Pacific/Tongatapu)" },
    {id: 69, ja_name: "協定世界時", en_name: "UTC", both: "協定世界時(UTC)" },


    



    
  ]
end 